apiVersion: v1
kind: Service
metadata:
  labels:
    app: avec
  name: avec
spec:
  type: NodePort
  ports:
  - name: "avec-service"
    port: 8000
    targetPort: 8000
    nodePort: 31000
  selector:
    app: avec
